# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(636, 500)
        Form.setStyleSheet("background-color: rgb(249, 211, 255);\n"
"font: 63 16pt \"Segoe UI Semibold\";")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 190, 191, 51))
        self.pushButton.setStyleSheet("background-color: rgb(179, 239, 255);\n"
"border-radius: 10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 190, 191, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(208, 255, 169);\n"
"border-radius: 10px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 19, 601, 451))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.506, x2:0.771144, y2:0.574, stop:0 rgba(226, 201, 255, 255), stop:1 rgba(192, 255, 248, 255));\n"
"font: 63 14pt \"Segoe UI Semibold\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 121, 51))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 221, 51))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 111, 51))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 211, 61))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 360, 251, 51))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.58, stop:0 rgba(168, 165, 255, 255), stop:1 rgba(255, 187, 255, 255));\n"
"border-radius:15px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(180, 50, 241, 31))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.630682, x2:1, y2:0.688, stop:0 rgba(253, 220, 220, 255), stop:1 rgba(204, 194, 255, 255));\n"
"border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 110, 241, 31))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.630682, x2:1, y2:0.688, stop:0 rgba(253, 220, 220, 255), stop:1 rgba(204, 194, 255, 255));\n"
"border-radius:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 190, 241, 31))
        self.lineEdit_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.630682, x2:1, y2:0.688, stop:0 rgba(253, 220, 220, 255), stop:1 rgba(204, 194, 255, 255));\n"
"border-radius:10px;")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 270, 241, 31))
        self.lineEdit_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.630682, x2:1, y2:0.688, stop:0 rgba(253, 220, 220, 255), stop:1 rgba(204, 194, 255, 255));\n"
"border-radius:10px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 19, 601, 451))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.557, stop:0 rgba(255, 190, 240, 255), stop:0.985075 rgba(255, 242, 174, 255), stop:1 rgba(174, 255, 192, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 181, 51))
        self.label_5.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 160, 121, 31))
        self.label_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(40, 230, 111, 31))
        self.label_7.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 350, 211, 61))
        self.pushButton_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(167, 255, 147);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 160, 241, 31))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.58, stop:0 rgba(168, 165, 255, 255), stop:1 rgba(255, 187, 255, 255));")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 230, 251, 31))
        self.lineEdit_6.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.58, stop:0 rgba(168, 165, 255, 255), stop:1 rgba(255, 187, 255, 255));")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 19, 601, 461))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(190, 40, 221, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(220, 140, 131, 181))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../Apps/imgonline-com-ua-Resize-4RpjThg5xvPF.png"))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Регистрация"))
        self.pushButton_2.setText(_translate("Form", "Авторизация"))
        self.label.setText(_translate("Form", "Ваше имя:"))
        self.label_2.setText(_translate("Form", "Придумайте логин:"))
        self.label_3.setText(_translate("Form", "Пароль:"))
        self.label_4.setText(_translate("Form", "Повторите пароль:"))
        self.pushButton_3.setText(_translate("Form", "Зарегистрироваться!"))
        self.label_5.setText(_translate("Form", "Авторизация"))
        self.label_6.setText(_translate("Form", "Пароль:"))
        self.label_7.setText(_translate("Form", "Логин:"))
        self.pushButton_4.setText(_translate("Form", "Авторизация"))
        self.label_8.setText(_translate("Form", "Вы в системе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
